config/routes.rb
Rails.application.routes.draw do
    root :to => 'memos#index'
    resources :memos
end

app/models/memo.rb
class Memo < ActiveRecord::Base
    validates :word, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:edit, :update, :destroy]
  def index
    @memo = Memo.new
    @memos = Memo.all
  end
  
  def create
    @memo = Memo.new(memo_params)
    if @memo.save
      @memos = Memo.all
      redirect_to '/memos'
    else
      @memos = Memo.all
      render 'index'
    end
  end
  
  def edit
  end
  
  def update
    if @memo.update(memo_params)
      redirect_to '/memos'
    else
      render 'edit'
    end
  end
  
  def destroy
    @memo.destroy
    redirect_to root_path
  end
  
  private 
  def memo_params
    params.require(:memo).permit(:word)
  end
  
  def set_memo
    @memo = Memo.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/memos/edit.html.erb
<h1>メッセージの編集</h1>
<%= form_for(@memo) do |f| %>
    メモ:
    <%= f.text_field :word %>
    <%= f.submit %>
<% end %>

<% if @memo.errors.any? %>
    <div id="error_explanation">
        <h2><%= @memo.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @memo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<%= link_to "戻る", '/' %>

app/views/memos/index.html.erb
<h1>Memo</h1>


<%= form_for(@memo) do |f| %>
    メモ:
    <%= f.text_field :word %>
    <%= f.submit %>
<% end %>

<% if @memo.errors.any? %>
    <div id="error_explanation">
        <h2><%= @memo.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @memo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>



<br>
<% @memos.each do |memo| %>
    メモ：<%= memo.word %>
    時刻：<%= memo.created_at %>
    (<%= link_to "編集", edit_memo_path(memo) %>
     <%= link_to "削除", memo, method: :delete %>)
    <br>
<% end %>